const express=require('express');
const path=require('path');
const Database=require('better-sqlite3');
const app=express();const PORT=process.env.PORT||3000;
const db=new Database(process.env.DB_PATH||path.join(__dirname,'data','rudrax.sqlite'));
db.exec(`CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,booking_key TEXT NOT NULL,movie TEXT NOT NULL,date TEXT NOT NULL,time TEXT NOT NULL,name TEXT NOT NULL,mobile TEXT NOT NULL,seats_json TEXT NOT NULL,total TEXT NOT NULL,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_booking_key ON bookings(booking_key);`);
app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
const conv=r=>({...r,key:r.booking_key,seats:JSON.parse(r.seats_json),createdAt:r.created_at});
app.get('/api/health',(q,s)=>s.json({ok:true}));
app.get('/api/bookings',(q,s)=>s.json(db.prepare('SELECT * FROM bookings ORDER BY created_at DESC').all().map(conv)));
app.post('/api/bookings',(q,s)=>{const b=q.body||{};if(!b.id||!b.movie||!b.date||!b.time||!b.name||!/^[0-9]{10}$/.test(String(b.mobile||''))||!Array.isArray(b.seats)||!b.seats.length)return s.status(400).json({error:'Invalid booking data'});const key=b.key||[b.movie,b.date,b.time].join('|');const rows=db.prepare('SELECT seats_json FROM bookings WHERE booking_key=?').all(key);const used=new Set();rows.forEach(r=>JSON.parse(r.seats_json).forEach(x=>used.add(x)));const clash=b.seats.find(x=>used.has(x));if(clash)return s.status(409).json({error:`Seat ${clash} is already booked.`});try{db.prepare('INSERT INTO bookings VALUES (?,?,?,?,?,?,?,?,?,?)').run(b.id,key,b.movie,b.date,b.time,b.name,String(b.mobile),JSON.stringify(b.seats),String(b.total||''),b.createdAt||new Date().toISOString());s.status(201).json({ok:true,id:b.id})}catch(e){s.status(409).json({error:'Booking could not be saved'})}});
app.delete('/api/bookings/:id',(q,s)=>{const r=db.prepare('DELETE FROM bookings WHERE id=?').run(q.params.id);s.json({ok:true,deleted:r.changes})});
app.delete('/api/bookings',(q,s)=>{db.prepare('DELETE FROM bookings').run();s.json({ok:true})});
app.post('/api/bookings/import',(q,s)=>{const list=q.body;if(!Array.isArray(list))return s.status(400).json({error:'Expected array'});const ins=db.prepare('INSERT OR REPLACE INTO bookings VALUES (?,?,?,?,?,?,?,?,?,?)');try{const tx=db.transaction(items=>{db.prepare('DELETE FROM bookings').run();for(const b of items){if(b.id&&b.movie&&b.date&&b.time&&b.name&&Array.isArray(b.seats))ins.run(b.id,b.key||[b.movie,b.date,b.time].join('|'),b.movie,b.date,b.time,b.name,String(b.mobile||''),JSON.stringify(b.seats),String(b.total||''),b.createdAt||new Date().toISOString())}});tx(list);s.json({ok:true})}catch(e){s.status(400).json({error:'Import failed'})}});
app.listen(PORT,()=>console.log('Rudrax Cinema running on '+PORT));
